name: unbound-telemetry
base: core20
version: git
grade: stable
summary: Unbound DNS resolver metrics exporter for Prometheus
description: |-
 Unbound DNS resolver metrics exporter for Prometheus

confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

apps:
  unbound-telemetry:
    command: daemon.start
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  unbound-telemetry:
    build-packages:
      - libssl-dev
      - pkg-config
    source: .
    plugin: rust
    prime:
      - bin/unbound-telemetry

  wrappers:
    plugin: dump
    source: .snapcraft/
